<!doctype html>
<html lang="fr">
  <head>
    <?php include("./components/head.php"); ?>
    <title>register new account</title>
  </head>
  <body>
    <div>
      <?php include("./components/header.php"); ?>
    </div>
    <main class="section container">
      <div class="container form">
        <h1 class="text-xlarge">C'est votre premiere commande ? <span class="text-primary">inscrivez vous !!!</span></h1>
        <form action="register.php" method="post">
          <div class="form-group">
            <label for="pseudo" id="pseudo" name="pseudo">Votre pseudo</label>
            <input id="pseudo" name="pseudo" type="text" class="form-control" required placeholder ="ex: il re della pizza in italia">
          </div>
          <div class="form-group">
            <label for="email" id="email" name= "email">Email utilisé pour la connexion</label>
            <input id="email" name="email" type="email" class="form-control"required placeholder="ex : pizza@Mamma.com">
          </div>
          <div class="form-group">
            <label for="password" id="password" name="password">Création de votre mot de passe</label>
            <input id="password" name="password" type="password" class="form-control" required placeholder="votre mot de passe ici">
          </div>
          <div class="button-center">
            <button type="submit" class="button">S'enregistrer</button>
          </div>
        </main>
        <div class="section section-pink">
          <div class="container">
            <h2 class="text-xlarge">Rencontrez la team</h2>
            <?php include("./components/team.php"); ?>
          </div>
        </div>
        <?php include("./components/footer.php"); ?>
      </body>
    </html>
